apiVersion: v1
kind: Pod
metadata:
  name: check-norm-pod
  labels:
    app: check-norm
spec:
  containers:
  - name: testing
    image: gitlab-registry.nrp-nautilus.io/jmduarte/hbb_interaction_network:latest
    # image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:52024b8a
    imagePullPolicy: Always
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 32Gi
        ephemeral-storage: 15Gi
        cpu: "8"
        nvidia.com/gpu: 1
      requests:
        memory: 30Gi
        ephemeral-storage: 15Gi
        cpu: "8"
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /j-jepa-vol
      name: check-norm-vol
    - mountPath: /dev/shm
      name: dshm
    ports:
    - containerPort: 6006  # Expose the TensorBoard port
  volumes:
    - name: check-norm-vol 
      persistentVolumeClaim:
        claimName: check-norm-vol 
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: "2Gi"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
                  - k8s-chase-ci-04.calit2.optiputer.net
                  - clu-fiona2.ucmerced.edu
                  - k8s-bharadia-03.sdsc.optiputer.net
                  - k8s-ravi-01.calit2.optiputer.net
                  - hcc-nrp-shor-c5825.unl.edu
                  - rci-nrp-gpu-08.sdsu.edu
                  - ry-gpu-02.sdsc.optiputer.net
                  - rci-nrp-gpu-03.sdsu.edu
                  - rci-nrp-gpu-01.sdsu.edu
                  - ry-gpu-04.sdsc.optiputer.net
                  - ry-gpu-07.sdsc.optiputer.net
          - key: nvidia.com/gpu.product
            operator: In
            values:
            # - NVIDIA-GeForce-GTX-1080
            # - NVIDIA-GeForce-GTX-1080-Ti
            # - NVIDIA-GeForce-GTX-2080-Ti
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-A10
            - NVIDIA-GeForce-RTX-4090